- name: Disable default site
  become: yes
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Add {{ guest.user }} to www-data group
  become: yes
  user: 
    name: "{{ guest.user }}"
    groups: www-data

- name: Setup site
  become: yes
  template: 
    src: host.j2 
    dest: "/etc/nginx/sites-available/{{ common.url }}.conf"

- name: Create symbolic link
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ common.url }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ common.url }}.conf"
    state: link

- name: Restart
  become: yes
  service: 
    name: nginx
    state: restarted
    enabled: yes