- name: install redmine
  hosts: ubuntu
  environment:
    PATH: "$HOME/.rbenv/bin::{{ ansible_env.PATH }}"
  vars_files: 
    - vars/common.yml
    - vars/guest.yml
    - vars/mysql.yml
    - vars/redmine.yml
    - vars/rbenv.yml
  roles:
    - system
    - rbenv
    - mysql
    - redmine
    - nginx
    - firewall