- name: Add an apt key for libnginx-mod-http-passenger
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7

- name: Add libnginx-mod-http-passenger repository
  become: yes
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main
    state: present

- name: Update apt
  become: yes
  apt:
    update_cache: yes

- name: install deps
  become: yes
  apt:
    name:
      - libssl-dev
      - mysql-server
      - python-mysqldb
      - ruby-full
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
      - build-essential
      - libmysqlclient-dev
      - imagemagick
      - libmagickwand-dev
      - libmagickcore-dev
      - libnginx-mod-http-passenger
      - python3-pip
      - nginx
    state: present

- name: Install bundler gem
  gem:
    name: bundler
    state: present

- name: Install mysql2 gem
  gem:
    name: mysql2
    state: present
