- name: Install pymsql
  become: true
  pip:
    name: pymysql
    state: present

- name: Mysql start
  service:
    name: mysql
    state: started
    enabled: yes

- name: Change the authentication plugin of MySQL root user to mysql_native_password
  become: yes
  shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password"
    WHERE user="root" AND host="localhost"'

- name: Flush Privileges
  become: yes
  shell: mysql -u root -e 'FLUSH PRIVILEGES'

- name: Set MySQL root Password
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql.root_password }}"
    state: present

- name: Restart mysql service
  become: yes
  service:
    name: mysql
    state: restarted

- name: Drop database first
  mysql_db:
    name: "{{ mysql.dbname }}"
    login_user: root
    login_password: "{{ mysql.root_password }}"
    state: absent

- name: Create database
  mysql_db:
    name: "{{ mysql.dbname }}"
    encoding: utf8
    login_user: root
    login_password: "{{ mysql.root_password }}"

- name: Create user for redmine
  mysql_user:
    name: "{{ mysql.user }}"
    password: "{{ mysql.password }}"
    login_user: root
    login_password: "{{ mysql.root_password }}"
    priv: "{{ mysql.dbname }}.*:ALL"